name: CD Pipeline - Despliegue en AWS EC2

# Este workflow se ejecutará automáticamente cada vez que se haga push o un commit en la rama main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Desplegar en Amazon EC2
    runs-on: ubuntu-latest

    steps:
      - name: Conectarse al EC2 por SSH y actualizar contenedores
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Conexión exitosa al servidor AWS EC2"
            
            # 1. Entrar a la carpeta de tu proyecto en el servidor Amazon Linux
            cd /home/ec2-user/Sis-Inmobiliaria-
            
            # 2. Descargar los últimos cambios que acabas de subir a GitHub
            echo "Descargando últimas actualizaciones desde GitHub..."
            git pull origin main
            
            # 3. Apagar y reconstruir los contenedores usando Docker Compose (Backend, Frontend y MySQL)
            echo "Reconstruyendo e iniciando contenedores de Docker..."
            docker-compose down
            docker-compose up -d --build
            
            echo "¡Despliegue finalizado con éxito en AWS!"
