name: CD Pipeline - Despliegue en AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Desplegar en Amazon EC2
    runs-on: ubuntu-latest

    steps:
      - name: Conectarse al EC2 por SSH y actualizar contenedores
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "--- Entrando a la carpeta del proyecto ---"
            cd /home/ec2-user/Sis-Inmobiliaria-
            
            echo "--- Limpiando contenedores previos ---"
            # Ahora que estamos en la carpeta, docker compose encontrará el archivo .yml
            docker compose down
            
            echo "--- Trayendo actualizaciones y desplegando ---"
            git pull origin main
            docker compose up -d --build
            
            echo "--- ¡Despliegue finalizado con éxito! ---"
